language: php

php:
  - 7.2
  - 7.3

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.5"

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
  - psql -c 'CREATE DATABASE kodus_db_cache_test;' -U postgres
  - mysql -e 'CREATE DATABASE kodus_db_cache_test;'

script: vendor/bin/phpunit
