language: php

php:
  - 8.0
  - 8.1

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.5"

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
  - psql -c 'CREATE DATABASE kodus_db_cache_test;' -U postgres
  - mysql -e 'CREATE DATABASE kodus_db_cache_test;'

script:
  - if [ $(phpenv version-name) = "8.1" ]; then vendor/bin/phpunit --coverage-clover ./clover.xml; else vendor/bin/phpunit; fi

after_script:
  - if [ $(phpenv version-name) = "8.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) = "8.1" ]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi
